### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by kmahyyg** [kmahyyg/asm-learning-notes#4]
## TODO LIST

- [x] | According to Unit 2's PPT, add more details to fix the status register.
- [x] | (Only can be used under IA-32 CPU) Add more types for data transfer commands: `movzx` `movsx` `xchg`

**Comment by kmahyyg** [comment]
- [x] | `ADD` command for halt-adder, `ADC` for full-adder

**Comment by kmahyyg** [comment]
- [x] |  `xadd`, exchange dest and src, finally `dest=dest+src` with halt-adder
- [x] | `sbb` full-subber, `sub` half-subber

`sbb` will sub the CF status page
